name: Code Quality

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up poetry
      run: |
        python -m pip install poetry
    - name: Install with dependencies
      run: |
        poetry install --all-extras
    - name: Lint with pylint
      run: |
        poetry run pylint $(git ls-files '*.py')

  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up poetry
      run: |
        python -m pip install poetry
    - name: Install with dependencies
      run: |
        poetry install --all-extras
    - name: Check with ruff
      run: |
        poetry run ruff check ./mqkit

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up poetry
      run: |
        python -m pip install poetry
    - name: Install with dependencies
      run: |
        poetry install --all-extras
    - name: Inspect with mypy
      run: |
        poetry run mypy --install-types --non-interactive ./mqkit
        poetry run mypy ./mqkit
